### ISSUE TITLE
Map on homepage does not scroll/pan left and right correctly

### ISSUE THREAD

**Issue by ainsofs** [ainsofs/central-ris#2]
There may be an issue with the date time line

**Comment by AgentJay** [comment]
The map has no dateline repeat, it's cut from the source (Mapbox). We need a new background map layer if you want dateline repeat. 
As this is a particularly important issue for the pacific, I'll look into other default layer options. In the meantime you can see some alternatives and the fact that it works by using the layer changer (top right of map).

**Comment by ainsofs** [comment]
Yes the dateline is important and I will try and find maps that correctly displays this. However, this issue refers to the fact that I cannot keep scrolling to the left without getting stuck on the pacific region (the same thing happens when I keep scrolling to the right)

**Comment by ainsofs** [comment]
I found that the issue is with the map base. When I use Mapbox World Light or Bright the issue occurs. When I use any of the google maps it scrolls correctly
